### ISSUE TITLE
Chapter 4 - jupyturtle module not installed first, nor explained

### ISSUE THREAD

**Issue by a1ch3mist** [AllenDowney/ThinkPythonSolutions#1]
Chapter 4 jumps to importing jupyturtle, without explaining that the module needs to be installed first, or that this chapter needs to be run in a specific environment (jupyter lite online isn't sufficient, and colab also says it's incompatible with the versions that installing jupyturtle requires).

I think this chapter needs to explain how to setup, or get into, an environment where it is ready to use "import jupyturtle"

**Comment by a1ch3mist** [comment]
I was able to get the environment set up by running your chapter 4 notebook in colab, which has the proper download installation instructions at first.

So, that may be the answer and could be mentioned in the book that it is required to do this with your full Chapter 4 notebook in colab. It's a requirement, not a recommendation - otherwise the book needs to explain how to set up the environment outside of that.

**Comment by AllenDowney** [comment]
Yes, the notebooks are meant to run in Colab. They can also run in other environments, but if someone is just learning Python, I strongly suggest they work in Colab and not deal with the frustrations of setting up other environments. And I don't want to weigh the book down with instructions for other environments. If people want to run the notebooks in other environments, they can swim at their own risk :)

**Comment by AllenDowney** [comment]
Sorry, I closed this too hastily. I realized that the book does not have a sentence that's supposed to be there -- I've added, "Instructions for downloading the jupyter module are in the notebook for this chapter". That should appear in the next update of the book. Thank you!
