### ISSUE TITLE
Chapter 8 - Wordle exercise

### ISSUE THREAD

**Issue by a1ch3mist** [AllenDowney/ThinkPythonSolutions#2]
The Wordle exercise description of check_word I think needs better explanation. It says "Write a function called check_word that takes a five-letter word and checks whether it could be the target word."

I had to check the solution to understand what was being asked.

My suggestion for clarity:
"Given what you know about the results of guessing SPADE and CLERK, write a function called check_word that takes a five-letter word and checks whether it could be the target word for this instance of Wordle."

(or something else clarifying). I didn't realize it was restricting that to the context of the guess of SPADE and CLERK.

**Comment by AllenDowney** [comment]
I've added a clarification. Thanks!
