### ISSUE TITLE
Chapter 8 - Monte Cristo - incorrect answer because some lines contain multiple instances

### ISSUE THREAD

**Issue by a1ch3mist** [AllenDowney/ThinkPythonSolutions#3]
In the Monte Cristo exercise it says to count the number of times those words appear in the text.

Your solution code and text actually count the number of lines that contain at least one of those words.

Since some lines contain multiple instances of the words (e.g. "Andrea turned pale, but as it was dark his pallor was not perceptible."), that is not the correct answer.

Either change the exercise to say count the number of lines, or make the solution a little more complex.

**Comment by AllenDowney** [comment]
Yup, good idea. Thanks!
